export default {
  "DarkSoulsItems": {
    "Consumibles": [
      "Alma guardiana fuego",
      "Bendición divina",
      "Calavera seductora",
      "Capullo flor verde",
      "Frasco Estus",
      "Hueso regreso",
      "Huevo vermífugo",
      "Humanidad",
      "Humanidades gemelas",
      "Maldición pasajera",
      "Musgo morado",
      "Musgo morado floreciente",
      "Musgo rojo sangre",
      "Piedra prisma",
      "Piedra purgadora",
      "Polvo reparación",
      "Resina pino dorada",
      "Resina pino negra",
      "Resina pino podrida",
      "Talismán de Lloyd"
    ],
    "Herramientas": [
      "Caja sin fondo",
      "Herramienta armaduras",
      "Herramienta armas",
      "Mortero reparaciones",
      "Orbe Ojo Negro",
      "Piedra cabeza dragón",
      "Piedra torso dragón",
      "Prismáticos",
      "Signo oscuro"
    ],
    "MaterialesMejora": [
      "Escama dragón",
      "Fragmento titanita",
      "Losa titanita",
      "Losa titanita azul",
      "Losa titanita blanca",
      "Losa titanita roja",
      "Titanita azul",
      "Titanita blanca",
      "Titanita demonio",
      "Titanita grande",
      "Titanita grande verde",
      "Titanita titilante",
      "Trozo titanita",
      "Trozo titanita rojo"
    ],
    "Proyectiles": [
      "Bomba fuego negra",
      "Bomba incendiaria",
      "Cuchillo arrojadizo",
      "Cuchillo venenoso",
      "Pastel bosta"
    ],
    "Municion": [
      "Flecha asesino dragones",
      "Flecha de fuego",
      "Flecha de madera",
      "Flecha grande",
      "Flecha Luz de Luna",
      "Flecha normal",
      "Flecha pluma",
      "Flecha veneno",
      "Perno de madera",
      "Perno francotirador",
      "Perno normal",
      "Perno pesado",
      "Perno relámpago"
    ],
    "Almas": {
      "Normales": [
        "Alma gran héroe",
        "Alma guerrero anónimo",
        "Alma héroe",
        "Alma no muerto perdido",
        "Alma venerable caballero",
        "Alma valiente caballero",
        "Gran Alma guerrero anónimo",
        "Gran Alma no muerto perdido",
        "Gran Alma valiente caballero",
        "Gran Alma venerable caballero"
      ],
      "Jefes": [
        "Alma de la mariposa lunar",
        "Alma de Gwyndolin",
        "Alma Gwyn, Señor ceniza",
        "Alma Ornstein",
        "Alma Priscilla",
        "Alma Quelaag",
        "Alma Sif",
        "Alma Smough",
        "Núcleo Golem hierro"
      ]
    },
    "ObjetosClave": [
      "Alma Señor",
      "Ascua cristal",
      "Ascua divina",
      "Ascua divina grande",
      "Ascua encantada",
      "Ascua f. caos",
      "Ascua f. grande",
      "Ascua grande",
      "Ascua mágica grande",
      "Ascua muy grande",
      "Ascua oscura",
      "Colgante roto",
      "Emblema Artorias",
      "Fragmento alma Señor legada",
      "Llave anexo",
      "Llave cámara cloacas",
      "Llave celda mazmorra",
      "Llave celda T. Archivos",
      "Llave celda torre archivo",
      "Llave Ciudad Infestada",
      "Llave extra archivo prisión",
      "Llave gran peregrino",
      "Llave jaula",
      "Llave maestra",
      "Llave misteriosa",
      "Llave P2 este Refugio",
      "Llave P2 oeste Refugio",
      "Llave Profundidades",
      "Llave puerta T. Archivos",
      "Llave residencia",
      "Llave ruinas Nuevo Londo",
      "Llave sello",
      "Llave sótano",
      "Llave sótano T. vigilancia",
      "Muñeca peculiar",
      "Rito del Avivado",
      "Vasija del Señor"
    ],
    "ObjetosMultijugador": [
      "Acusación",
      "Cristal separación negro",
      "Dedo reseco",
      "Libro de los culpables",
      "Lista sirvientes",
      "Medalla Luz Solar",
      "Ojo de la muerte",
      "Ojo Dragón",
      "Orbe Ojo Rojo roto",
      "Recuerdo represalia",
      "Saponita guía naranja",
      "Saponita señal blanca",
      "Saponita señal roja"
    ],
    "OtrosObjetos": [
      "Basura",
      "Colgante",
      "Moneda de cobre",
      "Moneda de plata",
      "Moneda de oro"
    ],
    "ObjetosDLC": [
      "Alma de Artorias",
      "Alma del guardián",
      "Alma de Manus",
      "Colgante de plata",
      "Cristal púrpura del cobarde",
      "Flecha grande de Gough",
      "Llave con emblema",
      "Seta de Elizabeth",
      "Talla \"Ayuda\"",
      "Talla \"Gracias\"",
      "Talla \"Hola\"",
      "Talla \"Lo siento\"",
      "Talla \"¡Muy bien!\""
    ]
  }
}
